=== audwinoyong/wsd-bookstore/web/WEB-INF/books.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <!-- Type declarations -->
    <xs:simpleType name="number">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="id">
        <xs:restriction id="ID" base="xs:integer">
            <xs:pattern value="[1-9][0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="title">
        <xs:restriction base="xs:string">
            <xs:pattern value="(([A-Za-z0-9]*)\s*)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="author">
        <xs:restriction base="xs:string">
            <xs:pattern value="(([A-Z][A-Za-z]*)\s*)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="category">
        <xs:restriction base="xs:string">
            <xs:pattern value="(([A-Za-z]*)\s*)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="condition">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:enumeration value="New"/>
            <xs:enumeration value="Good"/>
            <xs:enumeration value="Fair"/>
            <xs:enumeration value="Poor"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="isbn">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1}-\d{5}-\d{3}-\d{1}|\d{1}-\d{3}-\d{5}-\d{1}|\d{1}-\d{2}-\d{6}-\d{1}"/>
        </xs:restriction>
    </xs:simpleType> 
    <xs:simpleType name="year">
        <xs:restriction base="xs:int">
            <xs:pattern value="\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="publisher">
        <xs:restriction base="xs:string">
            <xs:pattern value="(([A-Z][A-Za-z]*)\s*)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="username">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z0-9]*)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="abstract">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9_.' !@#$%^*()_+={}|/:;,>?/`~ ])*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <!--            <xs:pattern value="([A-Za-z_\.]+)@([a-z\-]+\.)+([a-z\-]+)"/>-->
            <xs:pattern value="[a-zA-Z\._]+@[a-z\-]+(\.[a-z\-]+)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="availablilty">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:enumeration value="Available"/>
            <xs:enumeration value="Reserved"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Insert your element declarations here -->
    <xs:element name="books">
        <xs:complexType mixed="true">
            <xs:sequence>      
                <xs:element name="book" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="bookId" type="id"/>
                            <xs:element name="booktitle" type="title"/>
                            <xs:element name="author" type="author"/>
                            <xs:element name="category" type="category"/>
                            <xs:element name="condition" type="condition"/>
                            <xs:element name="isbn" type="isbn"/>
                            <xs:element name="publishYear" type="year"/>
                            <xs:element name="publisher" type="publisher"/>
                            <xs:element name="username" type="username"/>
                            <xs:element name="abstract" type="abstract"/> 
                            <xs:element name="availablilty" type="availablilty"/> 
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== audwinoyong/wsd-bookstore/web/WEB-INF/books.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="books.xsl"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book>
        <bookId>1</bookId>
        <booktitle>Good mates</booktitle>
        <author>Author Choi</author>
        <category>Science Fiction</category>
        <condition>New</condition>
        <isbn>1-23451-234-5</isbn>
        <publishYear>2018</publishYear>
        <publisher>Jimmy Rhee</publisher>
        <username>kevin</username>
        <abstract>A tale of good mates.</abstract>
        <availability>Reserved</availability>
    </book>
    <book>
        <bookId>2</bookId>
        <booktitle>Romeo and Juliet</booktitle>
        <author>William Shakespeare</author>
        <category>Romance</category>
        <condition>New</condition>
        <isbn>2-34567-789-1</isbn>
        <publishYear>1985</publishYear>
        <publisher>Jimmy Rhee</publisher>
        <username>kevin</username>
        <abstract>A legendary love story.</abstract>
        <availability>Reserved</availability>
    </book>
    <book>
        <bookId>3</bookId>
        <booktitle>Romeo and Juliet</booktitle>
        <author>William Shakespeare</author>
        <category>Romance</category>
        <condition>Good</condition>
        <isbn>2-34567-789-1</isbn>
        <publishYear>1985</publishYear>
        <publisher>Jimmy Rhee</publisher>
        <username>kevin</username>
        <abstract>A legendary love story.</abstract>
        <availability>Available</availability>
    </book>
    <book>
        <bookId>4</bookId>
        <booktitle>Good mates</booktitle>
        <author>Author Choi</author>
        <category>Science Fiction</category>
        <condition>Fair</condition>
        <isbn>1-23451-234-5</isbn>
        <publishYear>2018</publishYear>
        <publisher>Jimmy Rhee</publisher>
        <username>jimmy</username>
        <abstract>A tale of good mates.</abstract>
        <availability>Available</availability>
    </book>
    <book>
        <bookId>5</bookId>
        <booktitle>Triangle</booktitle>
        <author>Mac Barnett</author>
        <category>Picture Books</category>
        <condition>Poor</condition>
        <isbn>3-95231-883-7</isbn>
        <publishYear>1990</publishYear>
        <publisher>Jimmy Rhee</publisher>
        <username>kevin</username>
        <abstract>Meet Triangle, a geometry shape.</abstract>
        <availability>Available</availability>
    </book>
</books>
